# Generated by Django 4.1.7 on 2023-04-01 11:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('postTitle', models.TextField()),
                ('Neighborhood', models.TextField()),
                ('postalCode', models.CharField(max_length=15)),
                ('description', tinymce.models.HTMLField()),
                ('employementType', models.CharField(max_length=255)),
                ('direct_contact_recureters', models.BooleanField(default=False)),
                ('internship', models.BooleanField(default=False)),
                ('non_prof_org', models.BooleanField(default=False)),
                ('relo_ass_available', models.BooleanField(default=False)),
                ('telecommuting', models.BooleanField(default=False)),
                ('jobTitle', models.TextField()),
                ('compensation', models.TextField()),
                ('companyName', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
                ('emailPrivacy', models.CharField(max_length=255)),
                ('phoneCallOk', models.BooleanField(default=False)),
                ('smsOk', models.BooleanField(default=False)),
                ('showPhoneNumber', models.BooleanField(default=False)),
                ('phoneNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('contactName', models.CharField(blank=True, max_length=255, null=True)),
                ('showAddress', models.BooleanField(default=False)),
                ('streetName', models.CharField(blank=True, max_length=255, null=True)),
                ('crossStreet', models.CharField(blank=True, max_length=255, null=True)),
                ('cityAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/jobs/')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
                ('jobObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
            ],
        ),
    ]
